#!/usr/bin/env php
<?php

define('__ROOT__', __DIR__);

foreach (array(
             __DIR__.'/../../autoload.php', __DIR__.'/../vendor/autoload.php', __DIR__.'/vendor/autoload.php'
         ) as $file) {
    if (file_exists($file)) {
        define('DAC_COMPOSER_INSTALL', $file);

        break;
    }
}

require DAC_COMPOSER_INSTALL;

unset($argv[0]);

if (!isset($argv[1])) {
    echo 'Empty diagram config'.PHP_EOL;
    return;
}

if (strpos($argv[1], '--root=') === 0) {
    $_SERVER['ROOT_DIR'] = str_replace('--root=', '', $argv[1]);
    unset($argv[1]);
}

/**
 * @var \Nddcoder\Dac\Base\Diagram $diagram
 */
$diagram = null;

foreach ($argv as $file) {
    if (empty($diagram)) {
        $diagram = require($file);
    } else {
        /**
         * @var \Nddcoder\Dac\Base\Diagram $subDiagram
         */
        $subDiagram = require($file);
        $diagram->mergeInstructions($subDiagram->getInstructions());
    }
}

if (empty($diagram)) {
    echo 'Empty diagram config'.PHP_EOL;
} else {
    echo $diagram->render();
}
