#!/usr/bin/env php
<?php

use Dotenv\Dotenv;

foreach (array(
             __DIR__.'/../../autoload.php', __DIR__.'/../vendor/autoload.php', __DIR__.'/vendor/autoload.php'
         ) as $file) {
    if (file_exists($file)) {
        define('DAC_COMPOSER_INSTALL', $file);

        break;
    }
}

require DAC_COMPOSER_INSTALL;

foreach ([__DIR__, __DIR__.'/../../../'] as $file) {
    if (file_exists($file)) {
        Dotenv::createMutable($file)->load();
        break;
    }
}

unset($argv[0]);

/**
 * @var \Nddcoder\Base\Diagram $diagram
 */
$diagram = null;

foreach ($argv as $file) {
    if (empty($diagram)) {
        $diagram = require($file);
    } else {
        /**
         * @var \Nddcoder\Base\Diagram $subDiagram
         */
        $subDiagram = require($file);
        $diagram->mergeInstructions($subDiagram->getInstructions());
    }
}

if (empty($diagram)) {
    echo 'Empty diagram config'.PHP_EOL;
} else {
    echo $diagram->render();
}
